### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by haicenhacks** [russinnes/fsync-mdc1200-decode#2]
running `demod 0` (attempting to read from the sound card) immediately produces a segmentation fault. I have also tried piping output from gqrx via netcat, which also fails.

**Comment by russinnes** [comment]
Did you compile it on your machine?

**Comment by haicenhacks** [comment]
Yes. I ran the included build.sh. Are there dependencies other than sox and libpulse-dev?

**Comment by russinnes** [comment]
Try reinstalling pulseaudio

**Comment by stuartscott171** [comment]
Having the same issue, compiled on raspberry pi 3 machine using a usb soundcard. Tested this same card on my linux 64bit desktop machine, recompiled and works perfect.

**Comment by russinnes** [comment]
I've not tried it on an RPI, but I will and let you know what I find.

**Comment by stuartscott171** [comment]
Don't know if this helps but i kept halving the buffer size and found anything about 1024 caused this error. Program runs below this value but will not decode any MDC.

**Comment by russinnes** [comment]
Entire overhaul, try it now. Check the readme for an update.
